SELECT 
    VEICULO.PLACA, 
    VEICULO.ANO_FABRICACAO, 
    VEICULO.ANO_MODELO
FROM 
    VEICULO
JOIN 
    MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO
JOIN 
    FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE
WHERE 
    FABRICANTE.NOME_DO_FABRICANTE = 'RENAULT' 
    AND MODELO.NOME_MODELO NOT IN ('CLIO', 'SANDERO') 
    AND VEICULO.ANO_FABRICACAO < 2015;