UPDATE VEICULO
SET ANO_FABRICACAO = 2016
WHERE CODIGO_MODELO IN (
    SELECT CODIGO_MODELO
    FROM MODELO
    WHERE NOME_MODELO = 'Palio'
    AND CODIGO_FABRICANTE IN (
        SELECT CODIGO_DO_FABRICANTE
        FROM FABRICANTE
        WHERE NOME_DO_FABRICANTE = 'Fiat'
    )
)
AND ANO_FABRICACAO = 1996;