SELECT VEICULO.PLACA AS PLACA, 
MODELO.NOME_MODELO AS MODELO, 
FABRICANTE.NOME_DO_FABRICANTE AS FABRICANTE
FROM VEICULO
JOIN MODELO ON VEICULO.CODIGO_MODELO = MODELO.CODIGO_MODELO
JOIN FABRICANTE ON MODELO.CODIGO_FABRICANTE = FABRICANTE.CODIGO_DO_FABRICANTE;